server:
  port: 8081

# datasource
spring:
  datasource:
#oracle
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:BookmManage
#    username: veis
#    password: 123456

#mysql5.7
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.107:3306/bookmanage?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

# logback
logging:
  config: classpath:logback-spring.xml
  level:
    root: info

pagehelper:
    offsetAsPageNum: true
    pageSizeZero: true
    params: pageNum=pageHelperStart;pageSize=pageHelperRows;
    reasonable: false
    rowBoundsWithCount: true
    supportMethodsArguments: false
