server:
  port: 8090

# datasource
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:BookmManage
    username: veis
    password: 123456

# logback
logging:
  config: classpath:logback-spring.xml
  level:
    root: info

pagehelper:
    offsetAsPageNum: true
    pageSizeZero: true
    params: pageNum=pageHelperStart;pageSize=pageHelperRows;
    reasonable: false
    rowBoundsWithCount: true
    supportMethodsArguments: false
